// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2MBNFNIxyqvY-W5Z2GRZVvoVQQNv1OHc',
    appId: '1:858173087150:web:7130a2746a24c9b548fc3f',
    messagingSenderId: '858173087150',
    projectId: 'minhas-notas-flutter',
    authDomain: 'minhas-notas-flutter.firebaseapp.com',
    storageBucket: 'minhas-notas-flutter.appspot.com',
    measurementId: 'G-GQ0Q73FFDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXxq0R4cjeiLnt_i2rPPCM6DFpL6-1AJU',
    appId: '1:858173087150:android:81fc53d65c2289db48fc3f',
    messagingSenderId: '858173087150',
    projectId: 'minhas-notas-flutter',
    storageBucket: 'minhas-notas-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgsh2hpw816JPQG7QSDKO-MSSYqmL2pRw',
    appId: '1:858173087150:ios:739835c671ca40c548fc3f',
    messagingSenderId: '858173087150',
    projectId: 'minhas-notas-flutter',
    storageBucket: 'minhas-notas-flutter.appspot.com',
    iosClientId: '858173087150-d1g7c55o0rmf01mg0v85rtoh3lkdj337.apps.googleusercontent.com',
    iosBundleId: 'com.example.minhasnotas',
  );
}
